name: diety_
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animated_splash_screen: ^1.3.0
  awesome_dialog: ^3.2.0
  cloud_firestore: ^4.17.0
  cupertino_icons: ^1.0.8
  date_picker_timeline: ^1.2.6
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_database: ^10.5.2
  firebase_messaging: ^14.8.2
  firebase_storage: ^11.7.2
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.2.0
  flutter_spinkit: ^5.2.1
  gap: ^3.0.1
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  krill_to_lotin: ^0.0.5
  loading_animation_widget: ^1.2.1
  lottie: ^3.1.0
  page_transition: ^2.1.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - Images/