// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlLvnHxfl1dDBAhcM7NBNMzg031_nKSwM',
    appId: '1:1086387828729:web:8ff901f2f47cb3162c2f28',
    messagingSenderId: '1086387828729',
    projectId: 'diety-36af6',
    authDomain: 'diety-36af6.firebaseapp.com',
    storageBucket: 'diety-36af6.appspot.com',
    measurementId: 'G-WBRNBEJC26',
    databaseURL: 'https://diety-36af6-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJDyS_St5PHiUU5EJCII8d7jZjW3iKz9s',
    appId: '1:1086387828729:android:7afa4d91d785a4332c2f28',
    messagingSenderId: '1086387828729',
    projectId: 'diety-36af6',
    storageBucket: 'diety-36af6.appspot.com',
    databaseURL: 'https://diety-36af6-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAfoH-CXvgkqLUieAQ-EU_B4-gF5nX9Gs',
    appId: '1:1086387828729:ios:d90bc6d49b82ef7b2c2f28',
    messagingSenderId: '1086387828729',
    projectId: 'diety-36af6',
    storageBucket: 'diety-36af6.appspot.com',
    iosBundleId: 'com.example.diety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAfoH-CXvgkqLUieAQ-EU_B4-gF5nX9Gs',
    appId: '1:1086387828729:ios:d90bc6d49b82ef7b2c2f28',
    messagingSenderId: '1086387828729',
    projectId: 'diety-36af6',
    storageBucket: 'diety-36af6.appspot.com',
    iosBundleId: 'com.example.diety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlLvnHxfl1dDBAhcM7NBNMzg031_nKSwM',
    appId: '1:1086387828729:web:e3fe3a780f1213fe2c2f28',
    messagingSenderId: '1086387828729',
    projectId: 'diety-36af6',
    authDomain: 'diety-36af6.firebaseapp.com',
    storageBucket: 'diety-36af6.appspot.com',
    measurementId: 'G-PDRC9K37X0',
  );
}
